# Generated by Django 4.2.5 on 2023-09-14 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='name')),
                ('password', models.CharField(max_length=250, verbose_name='password')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('token', models.CharField(max_length=500, verbose_name='token')),
                ('token_expires', models.DateTimeField(blank=True, null=True, verbose_name='token_expires')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
            ],
        ),
    ]
